name: pp-website
channels:
  - conda-forge
dependencies:
  - arviz
  - bokeh
  - markdown
  - matplotlib
  - numpy
  - pandas=1.2
  - python=3.8
  - seaborn
  - streamlit=0.80
  - pip:
      - streamlit-disqus=0.1